import { test, expect, loadAllTestAccounts } from 'deepspace/testing'
import { projectRequest } from './helpers/records'

test.skip(loadAllTestAccounts().length < 2, 'Requires two usable DeepSpace test accounts.')
test('projects persist through create/edit and reject another user at the Records server', async ({ users }) => {
  test.setTimeout(120000)
  const [owner, other] = await users(2)
  const name = '__test-' + Date.now() + '__ Launch tool'
  let recordId = ''
  try {
    await owner.page.goto('/home')
    await expect(owner.page.getByRole('heading', { name: 'Your projects' })).toBeVisible()
    await expect(owner.page.getByText("You haven't created a launch project yet.", { exact: true })).toBeVisible()
    await owner.page.getByRole('link', { name: 'New Project', exact: true }).click()
    const create = owner.page.getByRole('button', { name: 'Create project', exact: true })
    await expect(create).toBeEnabled()
    await create.click()
    await expect(owner.page.getByText('Enter a project name.', { exact: true })).toBeVisible()
    await owner.page.getByLabel('Project name', { exact: true }).fill('  ' + name + '  ')
    await owner.page.getByLabel('Short description').fill('Launch planning tool')
    await owner.page.getByLabel('Target audience').fill('Independent developers')
    await owner.page.getByLabel('Problem solved').fill('Unclear launch positioning')
    await owner.page.getByLabel('Launch goal').selectOption('Get beta users')
    await owner.page.getByLabel('Website URL').fill('javascript:alert(1)')
    await create.click()
    await expect(owner.page.getByText('Enter a full http:// or https:// URL without credentials, or leave this blank.')).toBeVisible()
    await owner.page.getByLabel('Website URL').fill('')
    await owner.page.setViewportSize({ width: 390, height: 844 })
    expect(await owner.page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await owner.page.screenshot({ path: '.deepspace/phase1-form-mobile.png', fullPage: true })
    await owner.page.setViewportSize({ width: 1280, height: 900 })
    // Two synchronous submit events prove the ref lock, not just button disabling.
    await owner.page.locator('form').evaluate(form => {
      form.dispatchEvent(new Event('submit', { bubbles: true, cancelable: true }))
      form.dispatchEvent(new Event('submit', { bubbles: true, cancelable: true }))
    })
    await expect(owner.page).toHaveURL(/\/home$/)
    const card = owner.page.locator('article').filter({ has: owner.page.getByRole('heading', { name, exact: true }) })
    await expect(card).toHaveCount(1)
    await owner.page.reload()
    await expect(card).toHaveCount(1)
    await card.getByRole('link', { name: 'Open project' }).click()
    await expect(owner.page).toHaveURL(/\/projects\/[^/]+$/)
    recordId = new URL(owner.page.url()).pathname.split('/').pop()!
    await expect(owner.page.getByRole('heading', { name, exact: true })).toBeVisible()
    await owner.page.reload()
    await expect(owner.page.getByText('Unclear launch positioning', { exact: true })).toBeVisible()
    await owner.page.getByRole('button', { name: 'Edit project' }).click()
    await expect(owner.page.getByLabel('Project name', { exact: true })).toHaveValue(name)
    await owner.page.getByLabel('Project name', { exact: true }).fill(name + ' edited')
    await owner.page.getByLabel('Website URL').fill('https://example.com')
    await owner.page.getByRole('button', { name: 'Save changes' }).click()
    await expect(owner.page.getByText('Project changes saved.')).toBeVisible()
    await owner.page.reload()
    await expect(owner.page.getByRole('heading', { name: name + ' edited', exact: true })).toBeVisible()
    await expect(owner.page.getByRole('link', { name: 'https://example.com', exact: true })).toBeVisible()
    await owner.page.screenshot({ path: '.deepspace/phase1-overview.png', fullPage: true })
    await owner.page.getByRole('link', { name: '← Projects' }).click()
    await expect(owner.page.getByRole('heading', { name: name + ' edited', exact: true })).toBeVisible()

    await other.page.goto('/home')
    await expect(other.page.getByRole('heading', { name: 'Your projects' })).toBeVisible()
    await expect(other.page.getByRole('heading', { name: name + ' edited', exact: true })).toHaveCount(0)
    await other.page.goto('/projects/' + recordId)
    await expect(other.page.getByRole('heading', { name: 'Project unavailable' })).toBeVisible()
    expect((await projectRequest(other.page, 'read', recordId)).records).toEqual([])
    const update = await projectRequest(other.page, 'update', recordId)
    expect(update.success).toBe(false)
    expect(update.error).toContain('DENIED')
    const deletion = await projectRequest(other.page, 'delete', recordId)
    expect(deletion.success).toBe(false)
    expect(deletion.error).toContain('DENIED')
    await owner.page.reload()
    await expect(owner.page.getByRole('heading', { name: name + ' edited', exact: true })).toBeVisible()
    await owner.page.goto('/')
    await expect(owner.page.getByRole('link', { name: 'Go to dashboard' })).toBeVisible()
    // A brief without a generated kit can also be deleted from its workspace.
    await owner.page.goto('/projects/' + recordId)
    await owner.page.getByRole('button', { name: 'Delete Project', exact: true }).click()
    await owner.page.getByRole('dialog').getByRole('button', { name: 'Delete Project', exact: true }).click()
    await expect(owner.page).toHaveURL(/\/home$/)
    recordId = ''
    await owner.page.reload()
    await expect(owner.page.getByRole('heading', { name: 'Your projects' })).toBeVisible()
    await expect(owner.page.getByRole('heading', { name: name + ' edited', exact: true })).toHaveCount(0)
  } finally {
    if (recordId) {
      await owner.page.goto('/home')
      const cleanup = await projectRequest(owner.page, 'delete', recordId)
      expect(cleanup.success, cleanup.error).toBe(true)
    }
  }
})
